spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Journal App}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}

jwt:
  secret: ${JWT_SECRET}

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN}