spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Journal App}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: ${WEATHER_API_KEY}

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}

jwt:
  secret: ${JWT_SECRET}

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN}